package MainService;

import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.rmi.RemoteException;
import Publisher.PublisherInterface;
import Subscriber.SubscriberInterface;
import java.rmi.server.UnicastRemoteObject;

public class ServiceImplementation extends UnicastRemoteObject implements ServiceInterface {

    //Instance variables - Service's GUI
    //publishers - Map to store all the registered publishers along with their [String Key]
    //subscribers - Map to store all the registered subscribers along with their [String Key]
    //subscriptions - Map to store all the publishers a subscriber is subscribed to for e.g.
    //                Subscriber1 -> (Publisher1, Publisher2)
    //publisherSubscribers - Map to store all the subscribers of each publisher for e.g.
    //                       Publisher1 -> (Subscriber1, Subscriber2)
    //String Key - Is automatically generated by concatenating the name and the id if applicable 
    //             with a hash symbol as a delimiter
    private ServiceConsoleGUI GUI;
    private Map<String, PublisherInterface> publishers = new HashMap<>();
    private Map<String, SubscriberInterface> subscribers = new HashMap<>();
    private Map<String, ArrayList<PublisherInterface>> subscriptions = new HashMap<>();
    private Map<String, ArrayList<SubscriberInterface>> publisherSubscribers = new HashMap<>();

    //Default Constructor - Calls the super class to setup remote object
    public ServiceImplementation() throws RemoteException {
        super();
    }

    //setGUI - Initializes the service's GUI 
    public void setGUI(ServiceConsoleGUI GUI) {
        this.GUI = GUI;
    }

    //getNumberOfSubscribers - Returns the number of subscribers
    public int getNumberOfSubscribers(String name) {
        String keyPub = name + "#";
        ArrayList<SubscriberInterface> subscribers = publisherSubscribers.get(keyPub);
        
        if (subscribers == null) {
            return 0;
        } else {
            return subscribers.size();
        }
    }

    //getSubscribers - Returns an arraylist of all the registered subscribers
    public ArrayList<SubscriberInterface> getSubscribers() {
        return new ArrayList<>(subscribers.values());
    }

    //getPublisherKey - Returns the [String Key] of the publisher
    public String getPublisherKey(PublisherInterface pub) throws RemoteException {
        return pub.getName() + "#";
    }
    
    //getSubscriberKey - Returns the [String Key] of the subscriber
    public String getSubscriberKey(SubscriberInterface sub) throws RemoteException {
        return sub.getName() + "#" + sub.getId();
    }

    //hasPublisher - Checks if a publisher exists in the publishers array
    @Override
    public boolean hasPublisher(String name) throws RemoteException {
        String keyPub = name + "#";
        return publishers.containsKey(keyPub);
    }

    //hasPublisher - Checks if a subscriber exists in the subscribers array
    @Override
    public boolean hasSubscriber(String name, int id) throws RemoteException {
        String keySub = name + "#" + id;
        return subscribers.containsKey(keySub);
    }

    //PublisherInterface - Returns an object of type Publisher
    @Override
    public PublisherInterface getPublisher(String name) throws RemoteException {
        String keyPub = name + "#";
        return publishers.get(keyPub);
    }

    //getPublishers - Returns an arraylist of all the registered publishers
    @Override
    public ArrayList<PublisherInterface> getPublishers() throws RemoteException {
        return new ArrayList<>(publishers.values());
    }

    //registerPublisher - This function is responsible for registering publishers
    //                     and adding them to the publishers array
    //GUI.updateGUI() - Updates the Service GUI after these changes are done
    @Override
    public void registerPublisher(PublisherInterface pub) throws RemoteException {
        String keyPub = getPublisherKey(pub);
        
        if (!publishers.containsKey(keyPub)) {
            this.publishers.put(keyPub, pub);
        }
        
        GUI.updateGUI();
    }

    //registerSubscriber - This function is responsible for registering subscribers
    //                     and adding them to the subscribers array
    //GUI.updateGUI() - Updates the Service GUI after these changes are done
    @Override
    public void registerSubscriber(SubscriberInterface sub) throws RemoteException {
        String keySub = getSubscriberKey(sub);
        
        if (!subscribers.containsKey(keySub)) {
            this.subscribers.put(keySub, sub);
        }
        
        GUI.updateGUI();
    }

    //SubscriberInterface - Returns an object of type Subscriber
    @Override
    public SubscriberInterface getSubscriber(String name, int id) throws RemoteException {
        String keySub = name + "#" + id;
        return subscribers.get(keySub);
    }

    //subscribe - This function is responsible for subscribing users to a publisher
    //            by addig an instance of their object to the array publisherSubscribers
    //            and to the subscriptions
    //GUI.updateGUI() - Updates the Service GUI after these changes are done
    @Override
    public void subscribe(SubscriberInterface sub, PublisherInterface pub) throws RemoteException {
        String keySub = getSubscriberKey(sub);
        String keyPub = getPublisherKey(pub);

        if (!subscriptions.containsKey(keySub)) {
            this.subscriptions.put(keySub, new ArrayList<>());
        }
        this.subscriptions.get(keySub).add(pub);

        if (!publisherSubscribers.containsKey(keyPub)) {
            this.publisherSubscribers.put(keyPub, new ArrayList<>());
        }
        this.publisherSubscribers.get(keyPub).add(sub);
        
        GUI.updateGUI();
    }

    //unsubscribe - This function is responsible for unsubscribing users from a publisher
    //            by removing their instance object from publisherSubscribers and
    //            subscriptions array
    //GUI.updateGUI() - Updates the Service GUI after these changes are done
    @Override
    public void unsubscribe(SubscriberInterface sub, PublisherInterface pub) throws RemoteException {
        String keySub = getSubscriberKey(sub);
        String keyPub = getPublisherKey(pub);
        
        if (subscriptions.containsKey(keySub)) {
            if (subscriptions.get(keySub).contains(pub)) {
                this.subscriptions.get(keySub).remove(pub);
            }
        }

        if (publisherSubscribers.containsKey(keyPub)) {
            if (publisherSubscribers.get(keyPub).contains(sub)) {
                this.publisherSubscribers.get(keyPub).remove(sub);
            }
        }
        
        GUI.updateGUI();
    }

    //sendNotification - This function is responsible for sending notifications from publishers to
    //                   only the subscribed subscribers for this publisher
    @Override
    public void sendNotification(PublisherInterface pub, String notification) throws RemoteException {
        String keyPub = getPublisherKey(pub);

        ArrayList<SubscriberInterface> Subscribers = publisherSubscribers.get(keyPub);

        if (Subscribers != null) {
            for (int i = 0; i < Subscribers.size(); i++) {
                Subscribers.get(i).receiveNotification("[" + pub.getName() + "] " + notification);
            }
        }
    }

    //getSubscriptions - Returns an arraylist of all the publishers that a subscriber is subscribed
    @Override
    public ArrayList<PublisherInterface> getSubscriptions(SubscriberInterface sub) throws RemoteException {
        String keySub = getSubscriberKey(sub);
        
        if (subscriptions.containsKey(keySub)) {
            return subscriptions.get(keySub);
        } else {
            return new ArrayList<>();
        }
    }

    //getPublisherSubscribers - Returns an arraylist of all the subscribers that are subscribed to a specific publisher
    @Override
    public ArrayList<SubscriberInterface> getPublisherSubscribers(PublisherInterface pub) throws RemoteException {
        String keyPub = getPublisherKey(pub);
        
        if (publisherSubscribers.containsKey(keyPub)) {
            return publisherSubscribers.get(keyPub);
        } else {
            return new ArrayList<>();
        }
    }
}
